[tool.black]
    line-length = 88
    py36 = true
    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
    '''
    force-exclude = '''
    /(
        tests                   # files in this dir are ignored by pre-commit
    )\
    '''
